---

#
# bootstrap python3.11
#

- name: 'Run playbook-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-bootstrap_python.yml

#
# k3s
#

- name: 'Run playbook-01_first_server.yml'
  ansible.builtin.import_playbook: playbook-01_first_server.yml

- name: 'Run playbook-02_add_other_servers.yml'
  ansible.builtin.import_playbook: playbook-02_add_other_servers.yml

#
# Pi-Hole
#

- name: 'Run playbook-pihole_installation.yml'
  ansible.builtin.import_playbook: playbook-pihole_installation.yml
